### PR TITLE
use same benchmark pipeline

### PR DESCRIPTION
**Pull request by inisis**
use same benchmark pipeline to avoid extra download

### CODE REVIEW

**Review by ipiszy — COMMENTED** [review]
Thanks! cc @terrychenism to review

**Review by terrychenism — APPROVED** [review]
lgtm

**Comment by inisis** [comment]
@terrychenism @ipiszy Hi, can you tell me how to fix the lint failure, from the log I cannot figure out how to fix it

**Comment by terrychenism** [comment]
> @terrychenism @ipiszy Hi, can you tell me how to fix the lint failure, from the log I cannot figure out how to fix it

Can you rebase to latest main branch? I think it should be good to go~

**Comment by inisis** [comment]
@terrychenism Hi, it seems that workflow is blocked

**Comment by inisis** [comment]
| | Iters/s| GPU Memory(GB)|
| ----------- | ----------- |----------- |
| AITemplate | 57|6.3 |
| TensorRT(8522)| 58| 10.7|
| Pytorch| 8| 14|

**Pull request merged**
