### PR TITLE
AITemplate release 0.2

### PR DESCRIPTION
**Pull request by ipiszy**
Lots of new things are shipped!

1. FX2AIT: A connector between Pytorch and AITemplate. Check more details in https://github.com/facebookincubator/AITemplate/tree/main/fx2ait/README.md. Another connector between PT2 and AITemplate is WIP, stay tuned.
2. Data type support: Added support for fp32. Bfloat16 is WIP.
3. Profiling: Reduced profiling time for both GeMM and Conv kernels.
4. Tooling: Added simple per-op profiling. Improved error messages.
5. Examples: The StableDiffusion example has been updated.

### CODE REVIEW

**Review by yinghai — APPROVED** [review]
Need some lint fixes.

**Comment by vans163** [comment]
The link is invalid to fx2ait, either its the fx2ait branch that should be used in the link, or the folder is missing.

**Comment by ipiszy** [comment]
> The link is invalid to fx2ait, either its the fx2ait branch that should be used in the link, or the folder is missing.

Once this PR is merged, the link will be available.

**Comment by ipiszy** [comment]
> Need some lint fixes.

Will have a separate PR to fix it.

**Pull request merged**
