### PR TITLE
Disable cuda graph for SD

### PR DESCRIPTION
**Pull request by terrychenism**

### CODE REVIEW

**Comment by hwu36** [comment]
Cuda graph slows sd?

**Comment by terrychenism** [comment]
> Cuda graph slows sd?

No, there're memory leak issue when enable cuda graph. We'll look into it. 
cc @mikeiovine

**Comment by hwu36** [comment]
let me know if it is a cuda graph bug.  i can help.

**Comment by terrychenism** [comment]
> let me know if it is a cuda graph bug. i can help.

Thanks Haicheng! We'll check it from AIT side first.

**Review by antinucleon — APPROVED** [review]

**Pull request merged**
