### PR TITLE
Fix bug in func generation for model with dyn batch support

### PR DESCRIPTION
**Pull request by lygztq**

### CODE REVIEW

**Comment by antinucleon** [comment]
Thanks for contribution!

For lint, you can use `ufmt format python` to automatically format code

For ROCM part, before the AMD CI is set up, @asroy @shaojiewang @carlushuang could you manually test the PR?

**Comment by lygztq** [comment]
Not sure the kernel `cutlass_f16_s1688fprop_optimized_f16_64x64_32x2_nhwc_align_1_1` generated for sm75 is a valid kernel, back to static test for now

**Comment by lygztq** [comment]
close for now due to some permission problems

**Comment by shaojiewang** [comment]
> For ROCM part, before the AMD CI is set up, @asroy @shaojiewang @carlushuang could you manually test the PR?

Sure. Waiting for author's permission.

**Pull request closed without merging**
