### PR TITLE
SD 2.0

### PR DESCRIPTION
**Pull request by terrychenism**
3090TI perf: 
clip batch_size: 1, latency: 1.9384057521820068 ms
unet batch_size: 2, latency: 20.121392250061035 ms
vae batch_size: 1, latency: 25.589385509490967 ms

end2end 48.85it/s

### CODE REVIEW

**Comment by Suhail** [comment]
I may have done something wrong but I am getting weird images back:
image

**Comment by terrychenism** [comment]
> I may have done something wrong but I am getting weird images back:
> 
> image

I think you used the incorrect scheduler.

**Comment by antinucleon** [comment]
@terrychenism could you fix the linter? I think the other PR is also blocked by linter.

**Comment by Suhail** [comment]
> > I may have done something wrong but I am getting weird images back:
> 
> > 
> 
> > image
> 
> 
> 
> I think you used the incorrect scheduler.  

Is it not EulerDiscrete?

**Comment by vans163** [comment]
> > I may have done something wrong but I am getting weird images back:
> > image
> 
> I think you used the incorrect scheduler.

scheduler can only be EulerDiscrete for v2?

**Comment by yinghai** [comment]
Fixed the linter in https://github.com/facebookincubator/AITemplate/pull/106

**Comment by Suhail** [comment]
> I may have done something wrong but I am getting weird images back:
> 
> 
> 
> image
> 
> 

No longer an issue. I had a bug.

**Review by antinucleon — APPROVED** [review]

**Comment by DhruvThu** [comment]
@Suhail Can you let me know your bug? I am also getting the same results.
Thanks.

**Pull request merged**
