### PR TITLE
Refactor: change relative to absolute imports

### PR DESCRIPTION
**Pull request by kadeng**
Summary:
Applied a one-off refactoring script, to change all relative imports within AITemplate to absolute imports. Then ran arc lint to make sure formatting is correct.

### Why?

IDEs like VSCode or PyCharm have problems resolving the paths to packages imported via relative imports, as they don't know the basepath. Now we can navigate to all imported symbols using CMD+click on the symbol.

Here is the script. It is intended for one-off usage, so I did not bother with code style or reusability.

```
import os
import re
from pathlib import Path

def process_relative_imports(path, basepath, basepackage):
    path = os.path.abspath(str(path))
    basepath = os.path.abspath(str(basepath))
    if not path.startswith(basepath):
        return
    relpath = path[len(basepath) :].strip("/")
    pparts = relpath.split("/")

    def dot_replacer(match):
        dots = match.group(2)
        pkg = basepackage + ".".join(pparts[: -len(dots)])
        pkg = pkg.strip(".")
        replacement = match.group(1) + pkg + "." + match.group(3)
        return replacement.replace("..", ".")

    with open(path, "rt", encoding="utf8") as f:
        contents = f.read()
        rcontents = re.sub(
            r"(^from )(\.+)([^\.].*import .*$)",
            dot_replacer,
            contents,
            flags=re.MULTILINE,
        )
    with open(path, "wt", encoding="utf8") as f:
        f.write(rcontents)
    print(f"Wrote {path}")

if __name__ == "__main__":
    allpyfiles = [str(path) for path in Path(".").rglob("*.py")]
    for p in allpyfiles:
        print(p)
        if p.endswith("extra_cutlass_generator.py"):
            continue
        process_relative_imports(p, ".", "aitemplate.")

```

Differential Revision: D43715713

### CODE REVIEW

**Comment by apivovarov** [comment]
I do not see that issues in PyCharm. 
- `python`, `fx2ait` and `tests` folders are Market as Source Root in my PyCharm.
- Command⌘-Click works fine
- No red underscore in import blocks

`torch` and `torchvision` projects also uses imports which starts with `.` and `..`
- https://github.com/pytorch/pytorch/blob/master/torch/package/__init__.py
- https://github.com/pytorch/vision/blob/main/torchvision/io/__init__.py

**Comment by kadeng** [comment]
@apivovarov What I know is that in the IDEs I used, and specifically in Meta-internal vscode, relative imports led to autocomplete / code navigation issues. Strangely, this does not always happen or in every file, and of course it might depend on specifics of the config of the IDE, the project, the python language server if used etc. (Meta internal language server in this case).

Additionally,  I experienced that relative imports broke some automatic refactorings (Move / Rename package etc.) and autocomplete in PyCharm. That was on an older version of PyCharm, though, so maybe it's fixed by now. 

I like relative imports in other languages, but I never had these issues when I stuck to absolute and non-wildcard imports in python projects. Do you see any downsides to using them?

**Comment by apivovarov** [comment]
# PEP8
PEP8 imports classification is:
### Absolute imports 
```
from mypkg.sibling import example
```

### Explicit relative imports
```
from . import sibling
from .sibling import example
```

### Implicit relative imports 
```
import sibling
```
According to [PIP8](https://pep8.org/#imports) Imports section:
- Absolute imports are recommended
- Explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with **complex** package layouts where using absolute imports would be **unnecessarily** verbose
- Implicit relative imports should _never_ be used and have been removed in Python 3.

# Visual Studio Code

I just opened AITemplates folder in Visual Studio Code (1.76.0)
aitemplate **explicit relative** imports are recognized out of the box. Command(⌘)-click works fine, e.g.:
```
from ..compiler.test_strided_layernorm import build_ait_module, eval_pt
from . import acc_utils
from ...compiler.tensor_accessor import TensorAccessor
```

However, aitemplate **absolute** imports are **not** recognized and underlined in dark-yellow: 
```
from aitemplate.frontend import Tensor
from aitemplate.testing import detect_target
```
It is  probably because IDE has no idea where Source Roots are.

To solve the "issue" with aitemplate **absolute** imports I have to Go To
`File/Code > Preferences > Settings -> Extensions -> Pylance -> Extra Paths`
and add `python`, `fx2ait` and `tests` source folders to Extra Paths list.

# Conclusion
- Both Absolute imports and **Explicit** Relative imports are recommended to use in Python3. They have no issues.  IDEs such as PyCharm and VS Code are fully support them.
- Source folders should be explicitly Marked (or Added to Extra Path) in IDEs. It allows IDEs to understand where the Source Roots are located.

Based on that conclusions we can keep using both Absolute imports and **Explicit** Relative imports in Python 3 projects. There is no strong reasons to use Absolute imports instead of **Explicit** Relative imports.

**Comment by kadeng** [comment]
In this case it is likely that the vscode code navigation issues I faced had to do with the used (Meta internal) language server or it's configuration on our large monorepo. Might even have been a temporary glitch or something with the specific files / folders I was looking at. Switching to absolute imports resolved all code navigation issues for me, though. But of course that's not helping if it creates new problems for others who don't use a project setup with configured Python package search paths like you described.

I also read up on it in PEPs like the ones you mention, and while it is true that relative imports (especially implicit ones) have been discouraged  in Python 3 for a long time and were even considered for removal from the language, the "explicit" form of relative imports used here have been kind of un-discouraged not too long ago.

I will discuss and check Meta internally whether this was a bug or config issue of the language server and then come back here or close this PR.

**Comment by chenyang78** [comment]
> Based on that conclusions we can keep using both Absolute imports and **Explicit** Relative imports in Python 3 projects. It seems that there are no strong reasons for one approach versus another.

Thanks for the explanation and rationales, @apivovarov ! They make sense. On the other hand, I feel that absolute imports seem to be slightly more readable than relative imports (it might be arguable as well :)). Second, it might be good if we could take a unified way to import stuff in a project. If you don't have any strong objection, this PR looks acceptable to me. Any thoughts? Thanks!

**Pull request closed without merging**
