### PR TITLE
add back 2 group norm instances on rocm backend

### PR DESCRIPTION
**Pull request by shaojiewang**
@terrychenism @antinucleon Could we add back 2 group norm instances on rocm backend? Did they cause some issues?

### CODE REVIEW

**Comment by antinucleon** [comment]
Just make sure the PR passes tests on AMD GPU because we don't have CI for AMD GPU. Also, in v0.1.1 new profiler design increased profling speed by 4x, which I think ROCM backend should adopt as well.

**Review by antinucleon — APPROVED** [review]

**Comment by shaojiewang** [comment]
> Just make sure the PR passes tests on AMD GPU 

Sure, I'm doing this.

> Also, in v0.1.1 new profiler design increased profling speed by 4x, which I think ROCM backend should adopt as well.

Totally agree. We will adopt it on ROCM backend.

**Comment by antinucleon** [comment]
> > Just make sure the PR passes tests on AMD GPU
> 
> Sure, I'm doing this.
> 
> > Also, in v0.1.1 new profiler design increased profling speed by 4x, which I think ROCM backend should adopt as well.
> 
> Totally agree. We will adopt it on ROCM backend.

After test is done (unit test + sd example), just reply in this thread then I will merge it.

**Comment by shaojiewang** [comment]
close because CLA not signed.

**Pull request closed without merging**
