### PR TITLE
Stable Diffusion ControlNet

### PR DESCRIPTION
**Pull request by hlky**
# Stable Diffusion ControlNet

## Introduction

* ControlNetUNet2DConditionModel 
    * This is almost the same as UNet2DConditionModel, except that it accepts additional residuals as input.
* ControlNetModel 
    * This is the main ControlNet model that accepts ControlNet conditionings and outputs the additional down block and middle block residuals.

## Usage

Compiling ControlNet
```
python scripts/compile_controlnet.py --width 512 --height 512
```
Produces `tmp/ControlNetModel/test.so`

Compiling ControlNetUNet2DConditionModel
```
python scripts/compile_alt.py --width 512 --height 512 --controlnet True
```
Produces `tmp/ControlNetUNet2DConditionModel/test.so`

Inference
```
python scripts/demo_controlnet.py --width 512 --height 512 --steps 20
```

## Speed

3060 12GB, nvcc 11.6

ComfyUI xformers controlnet
```
100%|| 20/20 [00:04<00:00,  4.99it/s]
```

AITemplate controlnet
```
100%|| 20/20 [00:02<00:00,  8.02it/s]
```

## Notes

Is there a better way of specifying a list of Tensor as input with AITemplate? would be better. `mark_output` doesn't work with lists though, and when modified to loop if type == list there is an error elsewhere about list being unhashable, I didn't look further into that error though, maybe it's an easy fix

Not sure if this would be faster as a single module.

Static sizes only for now, will try to fix the dynamic sizes later.

Tested with `lllyasviel/sd-controlnet-canny`

SD2.x ControlNet unlikely to work.

### CODE REVIEW

**Comment by alexanderguzhva** [comment]
Hi @hlky, thanks for your PR. Would it be possible for you to convert line endings from Windows style to Unix style? Thanks.

**Comment by alexanderguzhva** [comment]
@hlky , would you please be able to apply the following patch https://gist.github.com/alexanderguzhva/b70813ec9862e8831e2c14eaf172fae0 to calm down the linter? Or can I do it on my own. Thanks!

**Comment by xiankgx** [comment]
Hi @hlky and all, how do I compile for dynamic image size?

**Comment by hlky** [comment]
@xiankgx Dynamic shape for ControlNet is not supported in this repo.

Support for ControlNet dynamic shape is available in [hlky/AIT](https://github.com/hlky/AIT). See the documentation [here](https://github.com/hlky/AIT/blob/main/docs/compile.md#controlnet).

I have yet to bring the changes upstream.

**Comment by xiankgx** [comment]
Hi @hlky , thank you so much for your help. I shall have a look at your repo. Much appreciated.

**Pull request closed without merging**
