### PR TITLE
SD example fix 

### PR DESCRIPTION
**Pull request by terrychenism**

### CODE REVIEW

**Comment by causten** [comment]
Tested and this PR allowed me to collect SD v2.0 /w Batch Size 1,2,4,8.  Dies on 16

**Comment by terrychenism** [comment]
end2end pipeline or benchmark.py?

**Comment by terrychenism** [comment]
> Tested and this PR allowed me to collect SD v2.0 /w Batch Size 1,2,4,8. Dies on 16

can you also post your err msg please?

**Comment by causten** [comment]
python3 scripts/compile.py --batch-size 16
python3 scripts/demo.py --benchmark true --batch 16

The compile seems to work but I get 

>   [19:54:01] model_container.cu:85: Init AITemplate Runtime with 1 concurrency
>   [19:54:02] model_interface.cu:200: Error: [SetValue] Dimension got value out of bounds; expected value to be in [1, 8], but got 16.

Thanks for getting the SD2 and BS1-4 working though!

**Comment by terrychenism** [comment]
Oh that's true. you'll need to enable batch size = 16 for clip model https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/src/compile_lib/compile_clip.py#L73

**Comment by terrychenism** [comment]
similar for unet and vae
https://github.com/facebookincubator/AITemplate/blob/main/examples/05_stable_diffusion/src/compile_lib/compile_unet.py#L75-L77

**Comment by apivovarov** [comment]
I noticed that the model name and type was changed multiple times in download_pipeline.py script in the recent PRs

A bit of history:
The model was set to `stabilityai/stable-diffusion-2-1-base` specifically on Feb 21 [PR286](https://github.com/facebookincubator/AITemplate/pull/286)

The reason ti use model `stabilityai/stable-diffusion-2-1-base` is the following:
- compile.py script has default compilation WxH as 512x512  (it corresponds to -base model).
- The latest model is 2.1 not 2.0 or 1.5

After that it was changed multiple times to `runwayml/stable-diffusion-v1-5` and `stabilityai/stable-diffusion-2`.

Any concerns to return the model name back to `stabilityai/stable-diffusion-2-1-base` in download_pipeline.py  script?
@terrychenism @ipiszy

**Pull request closed without merging**
